#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGAnimal
@end

@interface SWGAnimal : SWGObject


@property(nonatomic) NSString* noise;

@property(nonatomic) NSString* species;

@end
