#import <Foundation/Foundation.h>
#import "SWGAnimal.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGAnimalcontrollerApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGAnimalcontrollerApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGAnimalcontrollerApi*) sharedAPI;
///
///
/// getAnimal
/// 
///
/// 
///
/// @return SWGAnimal*
-(NSNumber*) getUsingGETWithCompletionBlock :
    (void (^)(SWGAnimal* output, NSError* error))completionBlock;
    


///
///
/// save
/// 
///
/// @param animal animal
/// 
///
/// @return 
-(NSNumber*) saveUsingPOSTWithCompletionBlock :(SWGAnimal*) animal 
    
    
    completionHandler: (void (^)(NSError* error))completionBlock;



@end
