#import <Foundation/Foundation.h>
#import "SWGExample.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGExamplecontrollerApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGExamplecontrollerApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGExamplecontrollerApi*) sharedAPI;
///
///
/// getExample
/// 
///
/// 
///
/// @return NSString*
-(NSNumber*) listUsingGETWithCompletionBlock :
    (void (^)(NSString* output, NSError* error))completionBlock;
    


///
///
/// save
/// 
///
/// @param example example
/// 
///
/// @return 
-(NSNumber*) saveUsingPOST1WithCompletionBlock :(SWGExample*) example 
    
    
    completionHandler: (void (^)(NSError* error))completionBlock;



@end
