#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGView.h"


@protocol SWGModelAndView
@end

@interface SWGModelAndView : SWGObject


@property(nonatomic) NSNumber* empty;

@property(nonatomic) NSObject* model;

@property(nonatomic) NSDictionary* /* NSString, NSObject */ modelMap;

@property(nonatomic) NSNumber* reference;

@property(nonatomic) SWGView* view;

@property(nonatomic) NSString* viewName;

@end
